version: '3.4'

services:
  ejercicionode:
    image: ejercicionode
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6969:6969
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
